spring:
  application:
    name: crypto-springboot-example
    version: 0.0.1.RC1
  profiles:
    active: local
  boot:
    admin:
      client:
        instance:
          # Client display name (인스턴스명)
          name: Client Server
          # 인스턴트 URL
          service-url: "http://localhost:8080"
        # admin server url
        url: "http://localhost:8090"
        # // 클라이언트 자동 등록
        auto-registration: true
        username: ${ADMIN_SERVER_USERNAME:admin}
        password: ${ADMIN_SERVER_PASSWORD:admin}

mybatis:
  mapper-locations:
    - mapper/**/*.xml
  type-aliases-package: com.freelife.domain, com.freelife.repository.mybatis
  type-handlers-package: com.freelife.repository.mybatis
  configuration:
    database-id: H2
    map-underscore-to-camel-case: false
    auto-mapping-unknown-column-behavior: FAILING
    cache-enabled: false
    local-cache-scope: statement
    arg-name-based-constructor-auto-mapping: true
    auto-mapping-behavior: full

crypto:
  path: crypto/default/config.json
  key: 8fc40b8e8aadbf4fe4cafe16dd52e1ea4a6abada47711097d59990eb4683b0cf
  iv: '00000000000000000000000000000000'
  seed: B/ITrfGl5P+haKEZtDbxTWj1cRDPsBjgifiFjWvl82Yrvk4KW491JLb4nuR0Nkc8cuSZAZLynLLcQGWg2/l0EMjQ6QxIQSmwc0OAmX0T/ubCD+QJsmzv5/ZdITg=
  credential: IQBq8beEoy9CwSu98/Y/ICkNwHSRnMwvH3bdcTCQbOXDyJxNxxQGZbQm4gYd69m/BeavXzK3k38toap7cmPQ1VJOq+hYfkOKWuq/xcot01QFS7R6gcNbn2QopcimgrX8raCjQWy41AzEdlBBzocO5Owvq25tBtKDnjAT37AGKKPQhtafY/xH4abvE4iBscKUk1b5wevtLzP5puR3lodCWO9Z1wS2bOCz4i6T1PnXzPcEAqllLrgQ741EvFR4vuWU31qzP4heGiNKKnYzAMIWVaCDJnPaAOPcmXuNf0ScOvWWMzS31E0jDueFi3oki/KU0NwdvSEMM65xtjrjn/rWsNpKIziRi/BhtPwSkS3W8U9wF2oEjbaCQQ3iVmdftRnRez3xzYLpLMwiLTgQZAmsTRq8nCcCuCdG8XWeaTgm7IK0xO4ZEuFIPUi1lOnvBEew3IWVJq4jlroSPQs7capqaw==
  hotel:
    path: crypto/hotel/config.json
    key: 794839940f4d20dac1b6508a165d1c8a69f5dcc8c7ef5466f81ce1b0244c4e3c
    iv: '00000000000000000000000000000000'
    seed: l7DmDZ3CIpc6eahWTEuImmbKCja51ZPdYyLHxDZdQHjeiEQNw4EShwmExqvpEocxIQC1XR+xfOVzbREddO05MB2ljeXiO+muOmlv8INJp+JsRgSZ6qKvL7mUVpg=
    credential: tDRfRjb56Dr6XOr8JMi7oUV3vQGuHhFpWK1Sd1PxqTkANkN0WY65c460wP10jKcBWmWRRp8DgK1EN1qS8849UqZ/jE4dyVVFe6F9yl6k5QakXouLKu2VDJPzfNVmdnTuGmdkJf7Vnp3K0xUtPTAGaY9PcJIoEepWEKnVsD5KI5Ahhgw2tw/55aqzl1fqiK/yuVkIgO7eYqiZEih437sSME8fwgZnEYY4XGttxKjxl24PTs44li3b2NwmQXrzIaTl4F+XiLh0ZIzRuXrk5hmGziyygfgMMtp/zakzQrQrp/xbkk3d8CSuEgRluaLbvr9b40agUEsWcEbABVSQr+tzkeutg3UnqoqTL8ZNhfvEMWFtjFnoyAnI2kFjCetJu1cEUvKNJX8UZUtTUhylofQM0/fezeWCEiMl66tkfMp1gcvQdPPqmXTIdV1A+H1jnohT2dt4qdLtS6RJWDq3wTTU1w==
  air:
    path: crypto/air/config.json
    key: 3974b3171e27aeba4543084e3d87c83eb4e8a27dc4209488c11c43464844f8ff
    iv: '00000000000000000000000000000000'
    seed: lnKBgBwFE3LTmupPuYFi1eCy0e0W32B2bzV7rFLL13ocnMniK9D7ZxK92ridgr1U/DVEPmDA++algUurzIarZm2hYd7VdWIZB0KILHASlfIutCe1KUailZJ80zs=
    credential: zK3+ydE6aHe+ZCjtnxGpK8pPl6GgyJgk1dYJb8F2cbZMeXfTGefINfP+7jeQi9vfR+Ic0c22VQuUwAiYNdpf1u/B64ebIxUWeC2mY0L/EK7nr1+7xC0yi+a5+NrtllqDMiy5SlqN+WMx2WFU0Gr1/1v2DdIgB1Vr8jc7ztT82kt2F9yQtv7p5RSbtdOpZ6bwu2mRYmc+byebokHahOvM6lyX483wDUTsc0lGecBPhHB/1C5ZxvS5RmFDBKkfwOsA5TjarzQJsRML5N0ME79se2nfU26eyHcxZHhKAEZgEbjQWoHCpqxXeNt0lNCKzMK+Y1FdZXgvKLsv6eMW28qpnavA2Sgs9a5eebpmmSLzjtwcEB4IurSk/YXKyMftwzkITIdpANZ+iFBm+7z3x9WVU5yfr2La4IAqdkoU7kX4IYM/YS7yjfFuf2NN9qx9mXIDDLScwidzd6Q0MrRIVhk/9w==

# P6Spy SpringBoot 자동 방식: https://jong-bae.tistory.com/23
decorator:
  datasource:
    p6spy:
      enable-logging: true
      custom-appender-class: com.p6spy.engine.spy.appender.Slf4JLogger
      logging: slf4j
      multiline: true

springdoc:
  open-api:
    version: 0.0.1.RC1
    info:
      title: Crypto SpringBoot Example
      description: Crypto 암복호화 라이브러리 사용 예제 프로젝트
      version: 0.0.1.RC1
      contact:
        name: Crypto
        email: crypto@freelife.com
        url: git@bitbucket.org:freelife/crypto-springboot-example.git
  api-docs:
    enabled: true
  swagger-ui:
    path: /docs
    deep-linking: true
    disable-swagger-default-url: true
    enabled: true
    persist-authorization: false
    operations-sorter: method
    tags-sorter: alpha
    show-common-extensions: true
    syntax-highlight:
      theme: obsidian
      activated: true
    show-extensions: true
    doc-expansion: list
    groups-order: asc
  model-and-view-allowed: true
  show-actuator: false

management:
  endpoints:
    web:
      exposure:
        # include: refresh, health, metrics, logfile, env
        include: "*"
  endpoint:
    health:
      show-details: always